### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by justinboohan** [ramybenaroya/ember-cli-lightbox#10]
When I try to install as per instructions i get this error on running ember g ember-cli-lightbox:

installing ember-cli-lightbox
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by pmlord** [comment]
Same for me today. Running –
- ember-cli: 2.12.3
- node: 6.10.2
- os: darwin x64

**Comment by pmlord** [comment]
Looks like pull request #9 is related

**Comment by ramybenaroya** [comment]
Fixed in https://github.com/ramybenaroya/ember-cli-lightbox/releases/tag/1.0.3
