### ISSUE TITLE
Failed to build when used in an addon

### ISSUE THREAD

**Issue by jeffrey008** [ramybenaroya/ember-cli-lightbox#12]
I have an addon that requires `ember-cli-lightbox`. When I run `ember serve` in consuming app it throws:
`TypeError: Path must be a string. Received undefined`

This is an know issue as described here: [https://github.com/ember-cli/ember-cli/issues/3718](https://github.com/ember-cli/ember-cli/issues/3718).

We need to fix this in `index.js` to allow nested addon usage.

**Comment by ramybenaroya** [comment]
I can't reproduce it. Please specify versions of
- ember-cli
- ember-cli-lightbox
- node
- npm
Also what kind of environment MAC/Windows/Linux.

**Comment by ramybenaroya** [comment]
I'll migrate the lightbox import to be done by ember-cli-node-assets like in:

**Comment by ramybenaroya** [comment]
Solved in https://github.com/ramybenaroya/ember-cli-lightbox/releases/tag/2.0.0
